[package]
name = "capsula-capture-git-repo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Capsula hook that captures Git repository information."
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["capsula", "capsula-hook"]
categories = ["development-tools"]

[dependencies]
capsula-core = { workspace = true }
git2 = "0.20.2"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ulid = { workspace = true }

[lints]
workspace = true
