[package]
name = "capsula-notify-slack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Capsula hook that sends notifications to Slack."
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["capsula", "capsula-hook", "slack"]
categories = ["development-tools"]

[dependencies]
capsula-core = { workspace = true }
glob = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
