# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for all rules.
default: true
line-length: false
first-line-h1: false
no-inline-html: false
no-alt-text: false
link-fragments: false
no-emphasis-as-heading: false
heading-increment: false
fenced-code-language: false
ol-prefix: false
no-trailing-punctuation: false
code-block-style: false
ul-indent:
  indent: 4
