#:schema ./capsula-schema.json

dotenv = ".env"
# server = "http://10.8.143.201:8500"

[vault]
name = "capsula"  # Should be unique in the storage

[[pre-run.hooks]]
id = "capture-machine"

[[pre-run.hooks]]
id = "capture-cwd"

[[pre-run.hooks]]
id = "capture-git-repo"
name = "capsula"
path = "."  # Relative to the project root.
allow_dirty = true

[[pre-run.hooks]]
id = "capture-file"
glob = "capsula.toml"
mode = "copy"
hash = "sha256"

[[pre-run.hooks]]
id = "capture-file"
glob = "Cargo.*"
mode = "copy"
hash = "sha256"

[[pre-run.hooks]]
id = "capture-file"
glob = "NON_EXISTENT_FILE"
mode = "copy"
hash = "sha256"

[[pre-run.hooks]]
id = "capture-env"
name = "HOME"

[[pre-run.hooks]]
id = "capture-command"
command = ["rustc", "--version"]

[[pre-run.hooks]]
id = "capture-command"
command = ["uv", "run", "python", "-c", "raise SystemExit(1)"]
abort_on_failure = false

[[pre-run.hooks]]
id = "notify-slack"
channel = "D0A61JQ7DFY"  # Channel ID of DM with Capsula Bot
# token is read from environment variable `SLACK_BOT_TOKEN`

[[post-run.hooks]]
id = "notify-slack"
channel = "D0A61JQ7DFY"  # Channel ID of DM with Capsula Bot
# token is read from environment variable `SLACK_BOT_TOKEN`
# Optional: attach files matching glob patterns (up to 10 files)
# attachment_globs = ["*.png", "outputs/*.jpg"]
attachment_globs = [".local/*.png"]

[[post-run.hooks]]
id = "capture-file"
glob = ".local/*.png"
mode = "copy"
hash = "sha256"
