[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/capsula-cli"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.89"
readme = "README.md"
repository = "https://github.com/shunichironomura/capsula"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1"
capsula-cli = { path = "crates/capsula-cli", version = "0.2.0" }
capsula-command-context = { path = "crates/capsula-command-context", version = "0.2.0" }
capsula-config = { path = "crates/capsula-config", version = "0.2.0" }
capsula-core = { path = "crates/capsula-core", version = "0.2.0" }
capsula-cwd-context = { path = "crates/capsula-cwd-context", version = "0.2.0" }
capsula-env-context = { path = "crates/capsula-env-context", version = "0.2.0" }
capsula-file-context = { path = "crates/capsula-file-context", version = "0.2.0" }
capsula-git-context = { path = "crates/capsula-git-context", version = "0.2.0" }
capsula-machine-context = { path = "crates/capsula-machine-context", version = "0.2.0" }
capsula-registry = { path = "crates/capsula-registry", version = "0.2.0" }
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
globwalk = "0.9"
names = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
shlex = "1"
sysinfo = "0.37"
thiserror = "2"
ulid = { version = "1", features = ["serde"] }
# whoami = "1"

[workspace.lints.rust]
