services:
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Variable POSTGRES_USER not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable POSTGRES_DB not set}
    ports:
      - "${POSTGRES_PORT?Variable POSTGRES_PORT not set}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CAPSULA_HOST=0.0.0.0
      - CAPSULA_PORT=3000
      - DATABASE_URL=postgresql://${POSTGRES_USER?Variable POSTGRES_USER not set}:${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}@postgres:5432/${POSTGRES_DB?Variable POSTGRES_DB not set}
      - CAPSULA_STORAGE_PATH=/data
    ports:
      - "${CAPSULA_PORT?Variable CAPSULA_PORT not set}:3000"
    depends_on:
      - postgres
    volumes:
      - app_data:/data

volumes:
  postgres_data:
  app_data:
