services:
  postgres:
    image: postgres:18@sha256:22c89fe0d0f507606260237fd55e51f6137f58b2d5bcf6152242b96d9fe8f9a4
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Variable POSTGRES_USER not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable POSTGRES_DB not set}
    ports:
      - "${POSTGRES_PORT?Variable POSTGRES_PORT not set}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CAPSULA_HOST=0.0.0.0
      - CAPSULA_PORT=8500
      - CAPSULA_MAX_BODY_SIZE=${CAPSULA_MAX_BODY_SIZE:-104857600}
      - DATABASE_URL=postgresql://${POSTGRES_USER?Variable POSTGRES_USER not set}:${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}@postgres:5432/${POSTGRES_DB?Variable POSTGRES_DB not set}
    ports:
      - "${CAPSULA_PORT?Variable CAPSULA_PORT not set}:8500"
    depends_on:
      - postgres
    volumes:
      - app_data:/app/storage

volumes:
  postgres_data:
  app_data:
