[package]
name = "capsula-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Configuration management for Capsula."
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["capsula", "config"]

[dependencies]
capsula-core = { workspace = true }
capsula-registry = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
