[package]
name = "capsula-capture-parameter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Capsula hook that captures a parameter value."
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["capsula", "capsula-hook"]
categories = ["development-tools"]

[dependencies]
capsula-capture-file = { workspace = true }
capsula-core = { workspace = true }
glob = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
ulid = { workspace = true }

[lints]
workspace = true
