[package]
name = "capsula-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Web server for managing and viewing Capsula runs"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["capsula", "server", "web"]
categories = ["web-programming::http-server"]

[dependencies]
askama = { workspace = true }
askama_web = { workspace = true }
axum = { workspace = true }
capsula-api-types = { workspace = true }
capsula-core = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
mime_guess = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
shlex = { workspace = true }
sql-json-path = { workspace = true }
sqlx = { workspace = true, features = ["migrate"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
testcontainers-modules = { workspace = true }

[lints]
workspace = true
