[package]
name = "capsula-cwd-context"
description = "A context provider that uses the current working directory."
keywords = ["capsula", "capsula-context"]
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
capsula-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
