[package]
name = "capsula-capture-file"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Capsula hook that captures file content."
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["capsula", "capsula-hook"]

[dependencies]
capsula-core = { workspace = true }
globwalk.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ulid = { workspace = true }

[lints]
workspace = true
