[package]
name = "capsula-capture-command"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Capsula context that captures command execution output."
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
capsula-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
