[package]
name = "capsula-file-context"
description = "A Capsula context that captures files."
keywords = ["capsula", "capsula-context"]
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
capsula-core = { workspace = true }
globwalk.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[lints]
workspace = true
