[package]
name = "capsula-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Terminal user interface for Capsula."
keywords = ["capsula", "tui"]
readme.workspace = true
repository.workspace = true
license.workspace = true
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = { workspace = true }
capsula-config = { workspace = true }
capsula-core = { workspace = true }
capsula-orchestration = { workspace = true }
capsula-registry = { workspace = true }
chrono = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
