[package]
name = "capsula-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Capsula hooks registry."
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
capsula-capture-command = { workspace = true }
capsula-capture-cwd = { workspace = true }
capsula-capture-env = { workspace = true }
capsula-capture-file = { workspace = true }
capsula-capture-git-repo = { workspace = true }
capsula-capture-machine = { workspace = true }
capsula-core = { workspace = true }
capsula-notify-slack = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
