[package]
name = "capsula-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Capsula contexts registry."
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
capsula-capture-command = { workspace = true, optional = true }
capsula-capture-cwd = { workspace = true, optional = true }
capsula-capture-env = { workspace = true, optional = true }
capsula-capture-file = { workspace = true, optional = true }
capsula-capture-git = { workspace = true, optional = true }
capsula-capture-machine = { workspace = true, optional = true }
capsula-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[features]
default = [
  "ctx-command",
  "ctx-cwd",
  "ctx-env",
  "ctx-file",
  "ctx-git",
  "ctx-machine"
]
ctx-command = ["dep:capsula-capture-command"]
ctx-cwd = ["dep:capsula-capture-cwd"]
ctx-env = ["dep:capsula-capture-env"]
ctx-file = ["dep:capsula-capture-file"]
ctx-git = ["dep:capsula-capture-git"]
ctx-machine = ["dep:capsula-capture-machine"]

[lints]
workspace = true
