[package]
name = "capsula-registry"
description = "A Capsula contexts registry."
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ["ctx-cwd", "ctx-git", "ctx-file", "ctx-env", "ctx-command", "ctx-machine"]
ctx-cwd = ["dep:capsula-cwd-context"]
ctx-git = ["dep:capsula-git-context"]
ctx-file = ["dep:capsula-file-context"]
ctx-env = ["dep:capsula-env-context"]
ctx-command = ["dep:capsula-command-context"]
ctx-machine = ["dep:capsula-machine-context"]

[dependencies]
capsula-core = { workspace = true }
capsula-cwd-context = { workspace = true, optional = true }
capsula-git-context = { workspace = true, optional = true }
capsula-file-context = { workspace = true, optional = true }
capsula-env-context = { workspace = true, optional = true }
capsula-command-context = { workspace = true, optional = true }
capsula-machine-context = { workspace = true, optional = true }

serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
