[package]
name = "capsula-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The command line interface for Capsula."
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["capsula", "cli"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "capsula"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
capsula-client = { workspace = true }
capsula-config = { workspace = true }
capsula-core = { workspace = true }
capsula-registry = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
names = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ulid = { workspace = true }

[lints]
workspace = true
